### ISSUE TITLE
Add option to write the MSRV as package.rust-version or package.metadata.msrv in the Cargo.toml

### ISSUE THREAD

**Issue by foresterre** [foresterre/cargo-msrv#138]
When we find a new MSRV, we should be able to add it to the Cargo manifest (Cargo.toml) automatically, saving a user time, similarly to `cargo add` etc. from `cargo-edit`.

By default:
* `package.rust-version` for Rust distributions where MSRV >=1.56
* `package.metadata.msrv` for Rust distributions where MSRV <1.56, as Cargo supports the rust-version field only since Rust distributions 1.56 or newer; for earlier versions it will produce an (unwanted) error.

**TODO's:**
* [x] #139
* [ ] Add CLI option, along the lines of `--write-manifest-msrv` (feel free to suggest a better name :D)  #368
* [x] Write MSRV to the correct key, depending on the MSRV found

**Under consideration:**
* Consider adding a flag when overwriting an existing msrv, e.g. `--no-override-manifest-msrv
  * NB: this option needs to handle the two different places (`package.rust-version` and `package.metadata.msrv`) where we can put the MSRV 
* Consider adding flag to always use `package.rust-version` regardless of the MSRV and warning Cargo will produce for versions <1.56.0.
* Consider adding flag to always use `package.metadata.msrv` regardless of the MSRV

**Example 1:**

Given, a found MSRV of version `1.56.0`, and the following manifest:
```toml
[package]
name = "v_1_56_0"
version = "0.1.0"
authors = ["foresterre <garm@ilumeo.com>"]
edition = "2021"

[dependencies]
```

We would write the the found MSRV to the manifest, and produce:
```toml
[package]
name = "v_1_56_0"
version = "0.1.0"
authors = ["foresterre <garm@ilumeo.com>"]
edition = "2021"
rust-version = "1.56.0"

[dependencies]
```

**Example 2:**

Given, a found MSRV of version `1.55.0`, and the following manifest:
```toml
[package]
name = "v_1_56_0"
version = "0.1.0"
authors = ["foresterre <garm@ilumeo.com>"]
edition = "2021"

[dependencies]
```

We would write the the found MSRV to the manifest, and produce:
```toml
[package]
name = "v_1_56_0"
version = "0.1.0"
authors = ["foresterre <garm@ilumeo.com>"]
edition = "2021"

[package.metadata]
msrv = "1.55.0"

[dependencies]
```
