### ISSUE TITLE
Setting MSRV for cargo workspaces

### ISSUE THREAD

**Issue by orhun** [foresterre/cargo-msrv#316]
Hello!

I have a [cargo workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) project and it has a `Cargo.toml` as following:

```toml
[workspace]
members = [
    "project1",
    "project2",
]
```

When I run `cargo msrv set 1.54.0`, `Cargo.toml` is updated like this:

```toml
package = { metadata = { msrv = "1.54.0" } }
[workspace]
members = [
    "project1",
    "project2",
]
```

I don't think this is a correct behavior since `cargo run` fails to parse the manifest:

```
error: failed to parse manifest at `Cargo.toml`

Caused by:
  missing field `name` for key `package`
```

I think there are 2 things that could be done here:
1- Parse `Cargo.toml` and fail gracefully if it only contains `[workspace]` section rather than `[package]`
2- Update MSRV's for the all members of the workspace (which might not be ideal for some cases)

What do you think? I'm happy to propose a PR about this.
