### ISSUE TITLE
feature: cargo-msrv rules (msrv by offset)

### ISSUE THREAD

**Issue by foresterre** [foresterre/cargo-msrv#725]
cargo msrv rules add <name from $supportedrules>  <values where values in $rule where $rule.id matches name>
    ... Could not add rule: 'x', 
    ...   Caused by: Duplicate, would override existing rule
    ...   Suggestion: "cargo msrv rules remove x", then rerun "cargo msrv rules add x value"

cargo msrv rules remove <name>

and in config, e..g Cargo.toml -> package.metadata.msrv-config

```toml
# Define the MSRV as (last release) - 2
[[package.metadata.msrv.rules]]
rule = "count-offset"
value = 2 
```

```toml
# Define the MSRV as 
[[package.metadata.msrv.rules]]
rule = "date-offset"
value = "18 months ago"
```

Consider:
* Maybe this "rules" section is too generic, and we should just add "msrv by offset" which can be "minus K releases" or "M months ago" (or other units).

* Do we resolve the rules? What do we do with incompatibilities? Can only one of the rules per category exist (assuming there are categories of course :))

* What rules should we want beyond offsets

* Rules are effectively filters
