### ISSUE TITLE
failure in GitLab runner: error: unexpected argument 'sh' found

### ISSUE THREAD

**Issue by wookietreiber** [foresterre/cargo-msrv#742]
original snippet from `.gitlab-ci.yml`:

```yml
msrv:
  stage: test
  image: foresterre/cargo-msrv:latest
  before_script:
    - rustc --version
    - cargo --version
    - cargo msrv --version
  script:
    - cargo msrv verify
```

error is: (full job log [here](https://gitlab.com/umcdev/smooth/-/jobs/4643384802))

```
error: unexpected argument 'sh' found
```

It's due to the way GitLab runner works with the entrypoint, which requires a shell, docs [here](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#override-the-entrypoint-of-an-image). The current image (as is) is not compatible with the GitLab runner workflow, because the entrypoint doesn't point to a shell but to the `cargo-msrv` binary. This was unexpected and I wondered for a bit where this `sh` came from. Luckily, the entrypoint can be overriden with configuration, this now passes (job log [here](https://gitlab.com/umcdev/smooth/-/jobs/4643487609)):

```yml
msrv:
  stage: test
  image:
    name: foresterre/cargo-msrv:latest
    entrypoint: [""]
  before_script:
    - rustc --version
    - cargo --version
    - cargo msrv --version
  script:
    - cargo msrv verify
```

I don't want to request to change the entrypoint you currently have in your Dockerfile, because that would likely screw with ppls current usage of the image/container. Would you be open to adding a CI section to the [cargo-msrv book](https://foresterre.github.io/cargo-msrv/index.html) so others have an easier reference in avoiding this? I'd be open to provide a PR. 

---

**Note:** I explicitly avoided doing `cargo install cargo-msrv` becausing building that **every** time the pipelines runs just takes too long, wastes energy, and would quickly consume the compute usage quota that the gitlab.com instance has.
