### ISSUE TITLE
Failure on Github Actions

### ISSUE THREAD

**Issue by BiagioFesta** [foresterre/cargo-msrv#809]
*I'm fairly certain that the issue does not originate from `cargo-msrv`. Please feel free to close this issue and direct me to a more appropriate place for seeking support.*

The [current CI run](https://github.com/BiagioFesta/wtransport/blob/03179203a942eecf7c5fa91483313c86b346d2ad/.github/workflows/msrv.yml) for my project is failing:

Workflow file:
```
name: MSRV

on:
  schedule:
    - cron: "0 9,18 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: cargo install cargo-msrv
      - name: Msrv Check WTransport
        run: cargo msrv --path wtransport --log-level trace verify
      - name: Msrv Check WTransport-Proto
        run: cargo msrv --path wtransport-proto --log-level trace verify
```

Run output:
```
Run cargo msrv --path wtransport --log-level trace verify
  cargo msrv --path wtransport --log-level trace verify
  shell: /usr/bin/bash -e {0}
  env:
    CARGO_TERM_COLOR: always
Fetching index
Verifying the Minimum Supported Rust Version (MSRV) for toolchain x86_64-unknown-linux-gnu
Using check command cargo check
   Failed check command cargo check didn't succeed
Crate source was found to be incompatible with its MSRV '1.64.0', as defined in 'wtransport/Cargo.toml'
Error: Process completed with exit code 1.
```

---

This issue started occurring on the same commit where the previous run was successful. 
The version of `cargo-msrv` remains the same. It runs without any issues locally.

I have tried `--log-level trace` for getting diagnostic information, but output is still same on Github action.

I believe I might be overlooking something, and it's possible that there have been changes in the execution environment, such as limitations in the CI container.

Am I missing something obvious, or do you have any suggestions for further investigation or obtaining additional diagnostic information?

Thank you
